# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setMarker_GlobalVarsInCPP <- function(t_impute_method, t_missing_cutoff, t_min_maf_marker, t_min_mac_marker, t_omp_num_threads, t_group, t_ifOutGroup, t_nGroup) {
    invisible(.Call(`_SPAmixPlus_setMarker_GlobalVarsInCPP`, t_impute_method, t_missing_cutoff, t_min_maf_marker, t_min_mac_marker, t_omp_num_threads, t_group, t_ifOutGroup, t_nGroup))
}

mainMarkerInCPP <- function(t_method, t_genoType, t_genoIndex, t_outputColumns, t_afFile) {
    .Call(`_SPAmixPlus_mainMarkerInCPP`, t_method, t_genoType, t_genoIndex, t_outputColumns, t_afFile)
}

exportAFModelInCPP <- function(t_method, t_genoType, t_genoIndex, t_outputFile) {
    invisible(.Call(`_SPAmixPlus_exportAFModelInCPP`, t_method, t_genoType, t_genoIndex, t_outputFile))
}

getGenoInCPP <- function(t_genoType, t_markerInfo, n, t_imputeMethod) {
    .Call(`_SPAmixPlus_getGenoInCPP`, t_genoType, t_markerInfo, n, t_imputeMethod)
}

getSpGenoInCPP <- function(t_genoType, t_markerInfo, n, t_imputeMethod) {
    .Call(`_SPAmixPlus_getSpGenoInCPP`, t_genoType, t_markerInfo, n, t_imputeMethod)
}

setSPAmixPlusobjInCPP <- function(t_resid, t_PCs, t_N, t_SPA_Cutoff, t_outLierList, t_sparseGRM, t_ResidMat) {
    invisible(.Call(`_SPAmixPlus_setSPAmixPlusobjInCPP`, t_resid, t_PCs, t_N, t_SPA_Cutoff, t_outLierList, t_sparseGRM, t_ResidMat))
}

setBGENobjInCPP <- function(t_bgenFileName, t_bgiFileName, t_SampleInBgen, t_SampleInModel, t_isSparseDosageInBgen, t_isDropVarNotWork, t_AlleleOrder) {
    invisible(.Call(`_SPAmixPlus_setBGENobjInCPP`, t_bgenFileName, t_bgiFileName, t_SampleInBgen, t_SampleInModel, t_isSparseDosageInBgen, t_isDropVarNotWork, t_AlleleOrder))
}

closeGenoInputInCPP <- function(t_genoType) {
    invisible(.Call(`_SPAmixPlus_closeGenoInputInCPP`, t_genoType))
}

setPLINKobjInCPP <- function(t_bimFile, t_famFile, t_bedFile, t_SampleInModel, t_AlleleOrder) {
    invisible(.Call(`_SPAmixPlus_setPLINKobjInCPP`, t_bimFile, t_famFile, t_bedFile, t_SampleInModel, t_AlleleOrder))
}

read_ukb_sample_ids_cpp <- function(geno_file) {
    .Call(`_SPAmixPlus_read_ukb_sample_ids_cpp`, geno_file)
}

load_phi_data_ukb_cpp <- function(phi_dir, ancestry_name, scenario) {
    .Call(`_SPAmixPlus_load_phi_data_ukb_cpp`, phi_dir, ancestry_name, scenario)
}

SPAmixPlus_local_ukb_high_performance_streaming_cpp <- function(geno_file, haplo_file, output_file, file_match_idx, R_matched, phi_A_mat, phi_B_mat, phi_C_mat, phi_D_mat, posOutlier, total_snps, save_interval, cutoff, MAF_cutoff, MAC_cutoff, verbose) {
    .Call(`_SPAmixPlus_SPAmixPlus_local_ukb_high_performance_streaming_cpp`, geno_file, haplo_file, output_file, file_match_idx, R_matched, phi_A_mat, phi_B_mat, phi_C_mat, phi_D_mat, posOutlier, total_snps, save_interval, cutoff, MAF_cutoff, MAC_cutoff, verbose)
}
read_bim_snps_by_chromosome <- function(bim_file) {
    .Call(`_SPAmixPlus_read_bim_snps_by_chromosome`, bim_file)
}

read_ukb_sample_info_large <- function(file_path) {
    .Call(`_SPAmixPlus_read_ukb_sample_info_large`, file_path)
}

read_ukb_snp_batch_stream <- function(hapcount_file, dosage_file, target_snps, max_snps_per_batch = 200L) {
    .Call(`_SPAmixPlus_read_ukb_snp_batch_stream`, hapcount_file, dosage_file, target_snps, max_snps_per_batch)
}

computePhiRatiosCPP <- function(hapcount_matrix, dosage_matrix, pair_idx1, pair_idx2, scenario, phi_threshold = 0.0, maf_cutoff = 0.2) {
    .Call(`_SPAmixPlus_computePhiRatiosCPP`, hapcount_matrix, dosage_matrix, pair_idx1, pair_idx2, scenario, phi_threshold, maf_cutoff)
}

estimatePhiStreamCPP <- function(hap_files, dos_files, bim_file, ancestry_id, scenario, pair_idx1, pair_idx2, chromosomes, snp_batch_size = 200L, phi_threshold = 0.0, maf_cutoff = 0.2) {
    .Call(`_SPAmixPlus_estimatePhiStreamCPP`, hap_files, dos_files, bim_file, ancestry_id, scenario, pair_idx1, pair_idx2, chromosomes, snp_batch_size, phi_threshold, maf_cutoff)
}
