// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// setMarker_GlobalVarsInCPP
void setMarker_GlobalVarsInCPP(std::string t_impute_method, double t_missing_cutoff, double t_min_maf_marker, double t_min_mac_marker, unsigned int t_omp_num_threads, arma::uvec t_group, bool t_ifOutGroup, unsigned int t_nGroup);
RcppExport SEXP _SPAmixPlus_setMarker_GlobalVarsInCPP(SEXP t_impute_methodSEXP, SEXP t_missing_cutoffSEXP, SEXP t_min_maf_markerSEXP, SEXP t_min_mac_markerSEXP, SEXP t_omp_num_threadsSEXP, SEXP t_groupSEXP, SEXP t_ifOutGroupSEXP, SEXP t_nGroupSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type t_impute_method(t_impute_methodSEXP);
    Rcpp::traits::input_parameter< double >::type t_missing_cutoff(t_missing_cutoffSEXP);
    Rcpp::traits::input_parameter< double >::type t_min_maf_marker(t_min_maf_markerSEXP);
    Rcpp::traits::input_parameter< double >::type t_min_mac_marker(t_min_mac_markerSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type t_omp_num_threads(t_omp_num_threadsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type t_group(t_groupSEXP);
    Rcpp::traits::input_parameter< bool >::type t_ifOutGroup(t_ifOutGroupSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type t_nGroup(t_nGroupSEXP);
    setMarker_GlobalVarsInCPP(t_impute_method, t_missing_cutoff, t_min_maf_marker, t_min_mac_marker, t_omp_num_threads, t_group, t_ifOutGroup, t_nGroup);
    return R_NilValue;
END_RCPP
}
// mainMarkerInCPP
Rcpp::List mainMarkerInCPP(std::string t_method, std::string t_genoType, std::vector<uint64_t> t_genoIndex, std::vector<std::string> t_outputColumns, std::string t_afFile);
RcppExport SEXP _SPAmixPlus_mainMarkerInCPP(SEXP t_methodSEXP, SEXP t_genoTypeSEXP, SEXP t_genoIndexSEXP, SEXP t_outputColumnsSEXP, SEXP t_afFileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type t_method(t_methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type t_genoType(t_genoTypeSEXP);
    Rcpp::traits::input_parameter< std::vector<uint64_t> >::type t_genoIndex(t_genoIndexSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type t_outputColumns(t_outputColumnsSEXP);
    Rcpp::traits::input_parameter< std::string >::type t_afFile(t_afFileSEXP);
    rcpp_result_gen = Rcpp::wrap(mainMarkerInCPP(t_method, t_genoType, t_genoIndex, t_outputColumns, t_afFile));
    return rcpp_result_gen;
END_RCPP
}
// exportAFModelInCPP
void exportAFModelInCPP(std::string t_method, std::string t_genoType, std::vector<uint64_t> t_genoIndex, std::string t_outputFile);
RcppExport SEXP _SPAmixPlus_exportAFModelInCPP(SEXP t_methodSEXP, SEXP t_genoTypeSEXP, SEXP t_genoIndexSEXP, SEXP t_outputFileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type t_method(t_methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type t_genoType(t_genoTypeSEXP);
    Rcpp::traits::input_parameter< std::vector<uint64_t> >::type t_genoIndex(t_genoIndexSEXP);
    Rcpp::traits::input_parameter< std::string >::type t_outputFile(t_outputFileSEXP);
    exportAFModelInCPP(t_method, t_genoType, t_genoIndex, t_outputFile);
    return R_NilValue;
END_RCPP
}
// getGenoInCPP
arma::mat getGenoInCPP(std::string t_genoType, Rcpp::DataFrame t_markerInfo, int n, std::string t_imputeMethod);
RcppExport SEXP _SPAmixPlus_getGenoInCPP(SEXP t_genoTypeSEXP, SEXP t_markerInfoSEXP, SEXP nSEXP, SEXP t_imputeMethodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type t_genoType(t_genoTypeSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type t_markerInfo(t_markerInfoSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< std::string >::type t_imputeMethod(t_imputeMethodSEXP);
    rcpp_result_gen = Rcpp::wrap(getGenoInCPP(t_genoType, t_markerInfo, n, t_imputeMethod));
    return rcpp_result_gen;
END_RCPP
}
// getSpGenoInCPP
arma::sp_mat getSpGenoInCPP(std::string t_genoType, Rcpp::DataFrame t_markerInfo, int n, std::string t_imputeMethod);
RcppExport SEXP _SPAmixPlus_getSpGenoInCPP(SEXP t_genoTypeSEXP, SEXP t_markerInfoSEXP, SEXP nSEXP, SEXP t_imputeMethodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type t_genoType(t_genoTypeSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type t_markerInfo(t_markerInfoSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< std::string >::type t_imputeMethod(t_imputeMethodSEXP);
    rcpp_result_gen = Rcpp::wrap(getSpGenoInCPP(t_genoType, t_markerInfo, n, t_imputeMethod));
    return rcpp_result_gen;
END_RCPP
}
// setSPAmixPlusobjInCPP
void setSPAmixPlusobjInCPP(arma::mat t_resid, arma::mat t_PCs, int t_N, double t_SPA_Cutoff, Rcpp::List t_outlierList, Rcpp::DataFrame t_sparseGRM, Rcpp::DataFrame t_ResidMat);
RcppExport SEXP _SPAmixPlus_setSPAmixPlusobjInCPP(SEXP t_residSEXP, SEXP t_PCsSEXP, SEXP t_NSEXP, SEXP t_SPA_CutoffSEXP, SEXP t_outLierListSEXP, SEXP t_sparsesGRMSEXP, SEXP t_ResidMatSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type t_resid(t_residSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type t_PCs(t_PCsSEXP);
    Rcpp::traits::input_parameter< int >::type t_N(t_NSEXP);
    Rcpp::traits::input_parameter< double >::type t_SPA_Cutoff(t_SPA_CutoffSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type t_outlierList(t_outLierListSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type t_sparseGRM(t_sparsesGRMSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type t_ResidMat(t_ResidMatSEXP);
    setSPAmixPlusobjInCPP(t_resid, t_PCs, t_N, t_SPA_Cutoff, t_outlierList, t_sparseGRM, t_ResidMat);
    return R_NilValue;
END_RCPP
}
// setBGENobjInCPP
void setBGENobjInCPP(std::string t_bgenFileName, std::string t_bgiFileName, std::vector<std::string> t_SampleInBgen, std::vector<std::string> t_SampleInModel, bool t_isSparseDosageInBgen, bool t_isDropVarNotWork, std::string t_AlleleOrder);
RcppExport SEXP _SPAmixPlus_setBGENobjInCPP(SEXP t_bgenFileNameSEXP, SEXP t_bgiFileNameSEXP, SEXP t_SampleInBgenSEXP, SEXP t_SampleInModelSEXP, SEXP t_isSparseDosageInBgenSEXP, SEXP t_isDropVarNotWorkSEXP, SEXP t_AlleleOrderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type t_bgenFileName(t_bgenFileNameSEXP);
    Rcpp::traits::input_parameter< std::string >::type t_bgiFileName(t_bgiFileNameSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type t_SampleInBgen(t_SampleInBgenSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type t_SampleInModel(t_SampleInModelSEXP);
    Rcpp::traits::input_parameter< bool >::type t_isSparseDosageInBgen(t_isSparseDosageInBgenSEXP);
    Rcpp::traits::input_parameter< bool >::type t_isDropVarNotWork(t_isDropVarNotWorkSEXP);
    Rcpp::traits::input_parameter< std::string >::type t_AlleleOrder(t_AlleleOrderSEXP);
    setBGENobjInCPP(t_bgenFileName, t_bgiFileName, t_SampleInBgen, t_SampleInModel, t_isSparseDosageInBgen, t_isDropVarNotWork, t_AlleleOrder);
    return R_NilValue;
END_RCPP
}
// closeGenoInputInCPP
void closeGenoInputInCPP(std::string t_genoType);
RcppExport SEXP _SPAmixPlus_closeGenoInputInCPP(SEXP t_genoTypeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type t_genoType(t_genoTypeSEXP);
    closeGenoInputInCPP(t_genoType);
    return R_NilValue;
END_RCPP
}
// setPLINKobjInCPP
void setPLINKobjInCPP(std::string t_bimFile, std::string t_famFile, std::string t_bedFile, std::vector<std::string> t_SampleInModel, std::string t_AlleleOrder);
RcppExport SEXP _SPAmixPlus_setPLINKobjInCPP(SEXP t_bimFileSEXP, SEXP t_famFileSEXP, SEXP t_bedFileSEXP, SEXP t_SampleInModelSEXP, SEXP t_AlleleOrderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type t_bimFile(t_bimFileSEXP);
    Rcpp::traits::input_parameter< std::string >::type t_famFile(t_famFileSEXP);
    Rcpp::traits::input_parameter< std::string >::type t_bedFile(t_bedFileSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type t_SampleInModel(t_SampleInModelSEXP);
    Rcpp::traits::input_parameter< std::string >::type t_AlleleOrder(t_AlleleOrderSEXP);
    setPLINKobjInCPP(t_bimFile, t_famFile, t_bedFile, t_SampleInModel, t_AlleleOrder);
    return R_NilValue;
END_RCPP
}

// read_ukb_sample_ids_cpp
std::vector<std::string> read_ukb_sample_ids_cpp(const std::string& geno_file);
RcppExport SEXP _SPAmixPlus_read_ukb_sample_ids_cpp(SEXP geno_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type geno_file(geno_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(read_ukb_sample_ids_cpp(geno_file));
    return rcpp_result_gen;
END_RCPP
}

// load_phi_data_ukb_cpp
SEXP load_phi_data_ukb_cpp(const std::string& phi_dir, const std::string& ancestry_name, const std::string& scenario);
RcppExport SEXP _SPAmixPlus_load_phi_data_ukb_cpp(SEXP phi_dirSEXP, SEXP ancestry_nameSEXP, SEXP scenarioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type phi_dir(phi_dirSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type ancestry_name(ancestry_nameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type scenario(scenarioSEXP);
    rcpp_result_gen = Rcpp::wrap(load_phi_data_ukb_cpp(phi_dir, ancestry_name, scenario));
    return rcpp_result_gen;
END_RCPP
}

// SPAmixPlus_local_ukb_high_performance_streaming_cpp
int SPAmixPlus_local_ukb_high_performance_streaming_cpp(const std::string& geno_file, const std::string& haplo_file, const std::string& output_file, const arma::uvec& file_match_idx, const arma::vec& R_matched, const arma::mat& phi_A_mat, const arma::mat& phi_B_mat, const arma::mat& phi_C_mat, const arma::mat& phi_D_mat, const arma::uvec& posOutlier, int total_snps, int save_interval, double cutoff, double MAF_cutoff, double MAC_cutoff, bool verbose);
RcppExport SEXP _SPAmixPlus_SPAmixPlus_local_ukb_high_performance_streaming_cpp(SEXP geno_fileSEXP, SEXP haplo_fileSEXP, SEXP output_fileSEXP, SEXP file_match_idxSEXP, SEXP R_matchedSEXP, SEXP phi_A_matSEXP, SEXP phi_B_matSEXP, SEXP phi_C_matSEXP, SEXP phi_D_matSEXP, SEXP posOutlierSEXP, SEXP total_snpsSEXP, SEXP save_intervalSEXP, SEXP cutoffSEXP, SEXP MAF_cutoffSEXP, SEXP MAC_cutoffSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type geno_file(geno_fileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type haplo_file(haplo_fileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type output_file(output_fileSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type file_match_idx(file_match_idxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type R_matched(R_matchedSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type phi_A_mat(phi_A_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type phi_B_mat(phi_B_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type phi_C_mat(phi_C_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type phi_D_mat(phi_D_matSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type posOutlier(posOutlierSEXP);
    Rcpp::traits::input_parameter< int >::type total_snps(total_snpsSEXP);
    Rcpp::traits::input_parameter< int >::type save_interval(save_intervalSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< double >::type MAF_cutoff(MAF_cutoffSEXP);
    Rcpp::traits::input_parameter< double >::type MAC_cutoff(MAC_cutoffSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(SPAmixPlus_local_ukb_high_performance_streaming_cpp(geno_file, haplo_file, output_file, file_match_idx, R_matched, phi_A_mat, phi_B_mat, phi_C_mat, phi_D_mat, posOutlier, total_snps, save_interval, cutoff, MAF_cutoff, MAC_cutoff, verbose));
    return rcpp_result_gen;
END_RCPP
}

// read_bim_snps_by_chromosome
List read_bim_snps_by_chromosome(const std::string& bim_file);
RcppExport SEXP _SPAmixPlus_read_bim_snps_by_chromosome(SEXP bim_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type bim_file(bim_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(read_bim_snps_by_chromosome(bim_file));
    return rcpp_result_gen;
END_RCPP
}

// read_ukb_sample_info_large
List read_ukb_sample_info_large(const std::string& file_path);
RcppExport SEXP _SPAmixPlus_read_ukb_sample_info_large(SEXP file_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file_path(file_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(read_ukb_sample_info_large(file_path));
    return rcpp_result_gen;
END_RCPP
}

// read_ukb_snp_batch_stream
List read_ukb_snp_batch_stream(const std::string& hapcount_file, const std::string& dosage_file, const std::vector<std::string>& target_snps, int max_snps_per_batch);
RcppExport SEXP _SPAmixPlus_read_ukb_snp_batch_stream(SEXP hapcount_fileSEXP, SEXP dosage_fileSEXP, SEXP target_snpsSEXP, SEXP max_snps_per_batchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type hapcount_file(hapcount_fileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dosage_file(dosage_fileSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type target_snps(target_snpsSEXP);
    Rcpp::traits::input_parameter< int >::type max_snps_per_batch(max_snps_per_batchSEXP);
    rcpp_result_gen = Rcpp::wrap(read_ukb_snp_batch_stream(hapcount_file, dosage_file, target_snps, max_snps_per_batch));
    return rcpp_result_gen;
END_RCPP
}

// computePhiRatiosCPP
List computePhiRatiosCPP(const arma::mat& hapcount_matrix, const arma::mat& dosage_matrix, const arma::uvec& pair_idx1, const arma::uvec& pair_idx2, const std::string& scenario, double phi_threshold, double maf_cutoff);
RcppExport SEXP _SPAmixPlus_computePhiRatiosCPP(SEXP hapcount_matrixSEXP, SEXP dosage_matrixSEXP, SEXP pair_idx1SEXP, SEXP pair_idx2SEXP, SEXP scenarioSEXP, SEXP phi_thresholdSEXP, SEXP maf_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type hapcount_matrix(hapcount_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dosage_matrix(dosage_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pair_idx1(pair_idx1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pair_idx2(pair_idx2SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type scenario(scenarioSEXP);
    Rcpp::traits::input_parameter< double >::type phi_threshold(phi_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type maf_cutoff(maf_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(computePhiRatiosCPP(hapcount_matrix, dosage_matrix, pair_idx1, pair_idx2, scenario, phi_threshold, maf_cutoff));
    return rcpp_result_gen;
END_RCPP
}

// estimatePhiStreamCPP
List estimatePhiStreamCPP(const std::vector<std::string>& hap_files, const std::vector<std::string>& dos_files, const std::string& bim_file, const std::string& ancestry_id, const std::string& scenario, const arma::uvec& pair_idx1, const arma::uvec& pair_idx2, const std::vector<int>& chromosomes, int snp_batch_size, double phi_threshold, double maf_cutoff);
RcppExport SEXP _SPAmixPlus_estimatePhiStreamCPP(SEXP hap_filesSEXP, SEXP dos_filesSEXP, SEXP bim_fileSEXP, SEXP ancestry_idSEXP, SEXP scenarioSEXP, SEXP pair_idx1SEXP, SEXP pair_idx2SEXP, SEXP chromosomesSEXP, SEXP snp_batch_sizeSEXP, SEXP phi_thresholdSEXP, SEXP maf_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type hap_files(hap_filesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type dos_files(dos_filesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type bim_file(bim_fileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type ancestry_id(ancestry_idSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type scenario(scenarioSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pair_idx1(pair_idx1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pair_idx2(pair_idx2SEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type chromosomes(chromosomesSEXP);
    Rcpp::traits::input_parameter< int >::type snp_batch_size(snp_batch_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type phi_threshold(phi_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type maf_cutoff(maf_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(estimatePhiStreamCPP(hap_files, dos_files, bim_file, ancestry_id, scenario, pair_idx1, pair_idx2, chromosomes, snp_batch_size, phi_threshold, maf_cutoff));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SPAmixPlus_setMarker_GlobalVarsInCPP", (DL_FUNC) &_SPAmixPlus_setMarker_GlobalVarsInCPP, 8},
    {"_SPAmixPlus_mainMarkerInCPP", (DL_FUNC) &_SPAmixPlus_mainMarkerInCPP, 5},
    {"_SPAmixPlus_exportAFModelInCPP", (DL_FUNC) &_SPAmixPlus_exportAFModelInCPP, 4},
    {"_SPAmixPlus_getGenoInCPP", (DL_FUNC) &_SPAmixPlus_getGenoInCPP, 4},
    {"_SPAmixPlus_getSpGenoInCPP", (DL_FUNC) &_SPAmixPlus_getSpGenoInCPP, 4},
    {"_SPAmixPlus_setSPAmixPlusobjInCPP", (DL_FUNC) &_SPAmixPlus_setSPAmixPlusobjInCPP, 7},
    {"_SPAmixPlus_setBGENobjInCPP", (DL_FUNC) &_SPAmixPlus_setBGENobjInCPP, 7},
    {"_SPAmixPlus_closeGenoInputInCPP", (DL_FUNC) &_SPAmixPlus_closeGenoInputInCPP, 1},
    {"_SPAmixPlus_setPLINKobjInCPP", (DL_FUNC) &_SPAmixPlus_setPLINKobjInCPP, 5},
    {"_SPAmixPlus_read_ukb_sample_ids_cpp", (DL_FUNC) &_SPAmixPlus_read_ukb_sample_ids_cpp, 1},
    {"_SPAmixPlus_load_phi_data_ukb_cpp", (DL_FUNC) &_SPAmixPlus_load_phi_data_ukb_cpp, 3},
    {"_SPAmixPlus_SPAmixPlus_local_ukb_high_performance_streaming_cpp", (DL_FUNC) &_SPAmixPlus_SPAmixPlus_local_ukb_high_performance_streaming_cpp, 16},
    {"_SPAmixPlus_read_bim_snps_by_chromosome", (DL_FUNC) &_SPAmixPlus_read_bim_snps_by_chromosome, 1},
    {"_SPAmixPlus_read_ukb_sample_info_large", (DL_FUNC) &_SPAmixPlus_read_ukb_sample_info_large, 1},
    {"_SPAmixPlus_read_ukb_snp_batch_stream", (DL_FUNC) &_SPAmixPlus_read_ukb_snp_batch_stream, 4},
    {"_SPAmixPlus_computePhiRatiosCPP", (DL_FUNC) &_SPAmixPlus_computePhiRatiosCPP, 7},
    {"_SPAmixPlus_estimatePhiStreamCPP", (DL_FUNC) &_SPAmixPlus_estimatePhiStreamCPP, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_SPAmixPlus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
